# ============================================================
# STEP 12: MODEL EXPLAINABILITY USING SHAP
# ============================================================
#
# This script:
# 1. Loads the final model generated by Step 11
# 2. Loads the Step 11 threshold configuration
# 3. Loads the test dataset
# 4. Generates SHAP values
# 5. Generates global feature importance
# 6. Generates critical-class feature importance
# 7. Generates a SHAP summary plot
# 8. Generates a local explanation for one test sample
# 9. Saves all explainability outputs
#
# ============================================================

import json
import warnings
from pathlib import Path

import joblib
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import shap

warnings.filterwarnings("ignore")


# ============================================================
# 1. PROJECT PATHS
# ============================================================

PROJECT_ROOT = Path(__file__).resolve().parents[2]

TEST_PATH = (
    PROJECT_ROOT
    / "data"
    / "processed"
    / "test_dataset.csv"
)

FINAL_MODEL_DIR = (
    PROJECT_ROOT
    / "models"
    / "final_models"
)

CONFIG_PATH = (
    PROJECT_ROOT
    / "outputs"
    / "step_11_final_model"
    / "final_threshold_configuration.json"
)

OUTPUT_DIR = (
    PROJECT_ROOT
    / "outputs"
    / "explainability"
)

OUTPUT_DIR.mkdir(
    parents=True,
    exist_ok=True
)


# ============================================================
# 2. CONFIGURATION
# ============================================================

TARGET_COLUMN = "Machine_Status_Code"

CRITICAL_CLASS = 2

MAX_SHAP_SAMPLES = 300

LOCAL_SAMPLE_POSITION = 0


# ============================================================
# 3. LOAD MODEL AND CONFIGURATION
# ============================================================

def load_model_and_configuration():
    """
    Load the final model generated by Step 11.

    The model filename is explicitly defined because the
    Step 11 configuration does not contain model-path details.
    """

    if not CONFIG_PATH.exists():
        print(
            "Warning: Step 11 configuration file was not found:"
        )
        print(CONFIG_PATH)
        print(
            "Continuing with the final model file directly."
        )

        config = {}

    else:
        with open(
            CONFIG_PATH,
            "r",
            encoding="utf-8"
        ) as file:
            config = json.load(file)

    # Actual model generated by Step 11
    model_path = (
        FINAL_MODEL_DIR
        / "LightGBM_No_SMOTE_Final.joblib"
    )

    if not model_path.exists():
        raise FileNotFoundError(
            "Final model was not found:\n"
            f"{model_path}\n\n"
            "Please run Step 11 first."
        )

    print(
        f"\nLoading final model from:\n{model_path}"
    )

    model = joblib.load(model_path)

    return model, config, model_path


# ============================================================
# 4. MODEL HELPER FUNCTIONS
# ============================================================

def get_model_classes(model):
    """
    Get the class labels used by the model.
    """

    if hasattr(model, "classes_"):
        return np.asarray(model.classes_)

    if hasattr(model, "named_steps"):

        for _, step in model.named_steps.items():

            if hasattr(step, "classes_"):
                return np.asarray(step.classes_)

    raise AttributeError(
        "Could not determine the model classes."
    )


def get_preprocessor(model):
    """
    Find the preprocessing step inside the model pipeline.
    """

    if not hasattr(model, "named_steps"):
        return None

    for step_name, step in model.named_steps.items():

        step_name_lower = step_name.lower()

        if (
            "preprocess" in step_name_lower
            or "transform" in step_name_lower
        ):
            return step

    return None


def get_final_estimator(model):
    """
    Find the underlying machine-learning estimator.

    Sampling steps such as SMOTE are ignored because they are
    only used during training.
    """

    if not hasattr(model, "named_steps"):
        return model

    ignored_steps = {
        "preprocessor",
        "preprocess",
        "transformer",
        "smote",
        "sampling",
    }

    for step_name, step in reversed(
        list(model.named_steps.items())
    ):

        if step_name.lower() in ignored_steps:
            continue

        if (
            hasattr(step, "predict_proba")
            or hasattr(step, "predict")
        ):
            return step

    return model


def transform_features(model, X_data):
    """
    Apply the preprocessing portion of the model pipeline.
    """

    preprocessor = get_preprocessor(model)

    if preprocessor is None:
        return X_data.to_numpy()

    transformed_data = preprocessor.transform(X_data)

    if hasattr(transformed_data, "toarray"):
        transformed_data = transformed_data.toarray()

    return np.asarray(transformed_data)


def get_feature_names(
    model,
    original_columns,
    transformed_data
):
    """
    Get feature names after preprocessing.
    """

    preprocessor = get_preprocessor(model)

    if preprocessor is not None:

        try:

            feature_names = list(
                preprocessor.get_feature_names_out()
            )

            if len(feature_names) == transformed_data.shape[1]:
                return feature_names

        except Exception:
            print(
                "Warning: Could not obtain transformed feature names."
            )

    if len(original_columns) == transformed_data.shape[1]:
        return list(original_columns)

    return [
        f"feature_{index}"
        for index in range(transformed_data.shape[1])
    ]


# ============================================================
# 5. SHAP HELPER FUNCTIONS
# ============================================================

def create_shap_explainer(estimator):
    """
    Create a SHAP TreeExplainer for tree-based models.
    """

    estimator_name = (
        estimator.__class__.__name__.lower()
    )

    tree_model_keywords = [
        "lightgbm",
        "lgbm",
        "xgb",
        "xgboost",
        "randomforest",
        "extratrees",
        "decisiontree",
        "gradientboosting",
        "histgradientboosting",
    ]

    is_tree_model = any(
        keyword in estimator_name
        for keyword in tree_model_keywords
    )

    if not is_tree_model:
        raise RuntimeError(
            "The final estimator is not recognized as a "
            "tree-based model."
        )

    try:

        return shap.TreeExplainer(estimator)

    except Exception as error:

        raise RuntimeError(
            "Could not create the SHAP TreeExplainer.\n"
            f"Reason: {error}"
        )


def extract_class_shap_values(
    shap_result,
    class_count
):
    """
    Convert SHAP values into a list containing one array
    per class.

    Supported formats:

    1. samples x features
    2. samples x features x classes
    3. classes x samples x features
    """

    values = np.asarray(shap_result.values)

    if values.ndim == 2:

        return [values]

    if values.ndim == 3:

        if values.shape[2] == class_count:

            return [
                values[:, :, class_index]
                for class_index in range(class_count)
            ]

        if values.shape[0] == class_count:

            return [
                values[class_index]
                for class_index in range(class_count)
            ]

    raise ValueError(
        "Unsupported SHAP output shape.\n"
        f"Received shape: {values.shape}\n"
        f"Number of classes: {class_count}"
    )


def save_json(data, output_path):
    """
    Save a dictionary as JSON.
    """

    with open(
        output_path,
        "w",
        encoding="utf-8"
    ) as file:

        json.dump(
            data,
            file,
            indent=4,
            default=str
        )


# ============================================================
# 6. MAIN WORKFLOW
# ============================================================

def main():

    print("\n" + "=" * 70)
    print("STEP 12: SHAP MODEL EXPLAINABILITY")
    print("=" * 70)

    # --------------------------------------------------------
    # Load test dataset
    # --------------------------------------------------------

    if not TEST_PATH.exists():

        raise FileNotFoundError(
            "Test dataset was not found:\n"
            f"{TEST_PATH}"
        )

    test_data = pd.read_csv(TEST_PATH)

    if TARGET_COLUMN not in test_data.columns:

        raise ValueError(
            f"Target column '{TARGET_COLUMN}' was not found.\n"
            f"Available columns: {list(test_data.columns)}"
        )

    X_test = test_data.drop(
        columns=[TARGET_COLUMN]
    )

    y_test = test_data[TARGET_COLUMN]

    print(
        f"\nTest dataset shape: {test_data.shape}"
    )

    print(
        f"Feature count: {X_test.shape[1]}"
    )

    print(
        f"Target column: {TARGET_COLUMN}"
    )

    # --------------------------------------------------------
    # Load final model and configuration
    # --------------------------------------------------------

    model, config, model_path = (
        load_model_and_configuration()
    )

    selected_model = config.get(
        "selected_model",
        "LightGBM"
    )

    selected_strategy = config.get(
        "selected_strategy",
        "No_SMOTE"
    )

    selected_threshold = config.get(
        "selected_threshold",
        0.15
    )

    print(
        f"\nSelected model: {selected_model}"
    )

    print(
        f"Selected strategy: {selected_strategy}"
    )

    print(
        f"Selected threshold: {selected_threshold}"
    )

    # --------------------------------------------------------
    # Identify estimator
    # --------------------------------------------------------

    estimator = get_final_estimator(model)

    print(
        "\nUnderlying estimator: "
        f"{estimator.__class__.__name__}"
    )

    # --------------------------------------------------------
    # Transform features
    # --------------------------------------------------------

    X_transformed = transform_features(
        model,
        X_test
    )

    feature_names = get_feature_names(
        model,
        X_test.columns,
        X_transformed
    )

    print(
        "Transformed feature matrix shape: "
        f"{X_transformed.shape}"
    )

    # --------------------------------------------------------
    # Select SHAP samples
    # --------------------------------------------------------

    total_samples = len(X_transformed)

    if total_samples == 0:

        raise ValueError(
            "The test dataset contains no samples."
        )

    shap_sample_count = min(
        MAX_SHAP_SAMPLES,
        total_samples
    )

    rng = np.random.default_rng(42)

    selected_positions = np.sort(
        rng.choice(
            total_samples,
            size=shap_sample_count,
            replace=False
        )
    )

    X_shap = X_transformed[
        selected_positions
    ]

    print(
        f"Samples selected for SHAP: "
        f"{len(X_shap)}"
    )

    # --------------------------------------------------------
    # Create SHAP explainer
    # --------------------------------------------------------

    print("\nCreating SHAP explainer...")

    explainer = create_shap_explainer(
        estimator
    )

    print("Calculating SHAP values...")

    shap_result = explainer(
        X_shap
    )

    model_classes = get_model_classes(model)

    class_count = len(model_classes)

    class_shap_values = extract_class_shap_values(
        shap_result,
        class_count
    )

    # --------------------------------------------------------
    # Save raw SHAP values
    # --------------------------------------------------------

    shap_output_path = (
        OUTPUT_DIR / "shap_values.npz"
    )

    np.savez_compressed(
        shap_output_path,
        **{
            f"class_{class_index}": values
            for class_index, values in enumerate(
                class_shap_values
            )
        },
        sample_positions=selected_positions,
        feature_names=np.asarray(feature_names)
    )

    print(
        f"\nSHAP values saved to:\n{shap_output_path}"
    )

    # --------------------------------------------------------
    # Global feature importance
    # --------------------------------------------------------

    global_rows = []

    for class_index, class_values in enumerate(
        class_shap_values
    ):

        mean_absolute_shap = np.mean(
            np.abs(class_values),
            axis=0
        )

        class_label = model_classes[class_index]

        for feature_index, importance in enumerate(
            mean_absolute_shap
        ):

            global_rows.append(
                {
                    "class": int(class_label),
                    "feature": feature_names[feature_index],
                    "mean_absolute_shap": float(importance),
                }
            )

    global_importance_df = pd.DataFrame(
        global_rows
    ).sort_values(
        by="mean_absolute_shap",
        ascending=False
    )

    global_importance_path = (
        OUTPUT_DIR
        / "global_feature_importance.csv"
    )

    global_importance_df.to_csv(
        global_importance_path,
        index=False
    )

    print(
        "Global feature importance saved to:\n"
        f"{global_importance_path}"
    )

    # --------------------------------------------------------
    # Critical-class feature importance
    # --------------------------------------------------------

    critical_indices = np.where(
        model_classes == CRITICAL_CLASS
    )[0]

    if len(critical_indices) == 0:

        raise ValueError(
            f"Critical class {CRITICAL_CLASS} was not found "
            f"in model classes: {model_classes.tolist()}"
        )

    critical_class_index = int(
        critical_indices[0]
    )

    critical_values = class_shap_values[
        critical_class_index
    ]

    critical_importance = np.mean(
        np.abs(critical_values),
        axis=0
    )

    top_count = min(
        20,
        len(feature_names)
    )

    top_indices = np.argsort(
        critical_importance
    )[-top_count:]

    plt.figure(
        figsize=(10, 8)
    )

    plt.barh(
        range(top_count),
        critical_importance[top_indices]
    )

    plt.yticks(
        range(top_count),
        [
            feature_names[index]
            for index in top_indices
        ]
    )

    plt.xlabel(
        "Mean absolute SHAP value"
    )

    plt.ylabel(
        "Feature"
    )

    plt.title(
        "Top Features Influencing Critical-Class Predictions"
    )

    plt.tight_layout()

    critical_plot_path = (
        OUTPUT_DIR
        / "critical_class_feature_importance.png"
    )

    plt.savefig(
        critical_plot_path,
        dpi=300,
        bbox_inches="tight"
    )

    plt.close()

    print(
        "Critical-class feature plot saved to:\n"
        f"{critical_plot_path}"
    )

    # --------------------------------------------------------
    # SHAP summary plot for critical class
    # --------------------------------------------------------

    summary_plot_path = (
        OUTPUT_DIR
        / "critical_class_shap_summary.png"
    )

    try:

        shap.summary_plot(
            critical_values,
            X_shap,
            feature_names=feature_names,
            show=False
        )

        plt.tight_layout()

        plt.savefig(
            summary_plot_path,
            dpi=300,
            bbox_inches="tight"
        )

        plt.close()

        print(
            "SHAP summary plot saved to:\n"
            f"{summary_plot_path}"
        )

    except Exception as error:

        plt.close()

        print(
            "Warning: SHAP summary plot could not be generated."
        )

        print(
            f"Reason: {error}"
        )

    # --------------------------------------------------------
    # Local explanation
    # --------------------------------------------------------

    if not (
        0 <= LOCAL_SAMPLE_POSITION < total_samples
    ):

        raise IndexError(
            "LOCAL_SAMPLE_POSITION is outside the test dataset."
        )

    local_position = LOCAL_SAMPLE_POSITION

    local_transformed = X_transformed[
        local_position:local_position + 1
    ]

    print(
        "\nCalculating local explanation..."
    )

    local_result = explainer(
        local_transformed
    )

    local_class_values = extract_class_shap_values(
        local_result,
        class_count
    )

    local_critical_values = local_class_values[
        critical_class_index
    ][0]

    local_absolute_values = np.abs(
        local_critical_values
    )

    sorted_indices = np.argsort(
        local_absolute_values
    )[::-1]

    local_rows = []

    for feature_index in sorted_indices:

        local_rows.append(
            {
                "feature": feature_names[feature_index],
                "shap_value_for_critical_class": float(
                    local_critical_values[feature_index]
                ),
                "absolute_shap_value": float(
                    local_absolute_values[feature_index]
                ),
            }
        )

    local_explanation_df = pd.DataFrame(
        local_rows
    )

    local_explanation_path = (
        OUTPUT_DIR
        / "local_explanation.csv"
    )

    local_explanation_df.to_csv(
        local_explanation_path,
        index=False
    )

    print(
        "Local explanation saved to:\n"
        f"{local_explanation_path}"
    )

    # --------------------------------------------------------
    # Local prediction metadata
    # --------------------------------------------------------

    local_prediction = model.predict(
        X_test.iloc[[local_position]]
    )[0]

    local_probability = None

    if hasattr(model, "predict_proba"):

        local_probability = (
            model.predict_proba(
                X_test.iloc[[local_position]]
            )[0].tolist()
        )

    local_metadata = {
        "test_row_position": int(local_position),
        "model_path": str(model_path),
        "selected_model": selected_model,
        "selected_strategy": selected_strategy,
        "selected_threshold": selected_threshold,
        "actual_label": int(
            y_test.iloc[local_position]
        ),
        "model_prediction": int(local_prediction),
        "critical_class": CRITICAL_CLASS,
        "model_classes": model_classes.tolist(),
        "prediction_probabilities": local_probability,
        "original_features": {
            str(key): str(value)
            for key, value in X_test.iloc[
                local_position
            ].to_dict().items()
        },
    }

    local_metadata_path = (
        OUTPUT_DIR
        / "local_explanation_metadata.json"
    )

    save_json(
        local_metadata,
        local_metadata_path
    )

    print(
        "Local explanation metadata saved to:\n"
        f"{local_metadata_path}"
    )

    # --------------------------------------------------------
    # General metadata
    # --------------------------------------------------------

    general_metadata = {
        "model_path": str(model_path),
        "selected_model": selected_model,
        "selected_strategy": selected_strategy,
        "selected_threshold": selected_threshold,
        "target_column": TARGET_COLUMN,
        "critical_class": CRITICAL_CLASS,
        "test_rows": int(len(X_test)),
        "shap_rows": int(len(X_shap)),
        "transformed_feature_count": int(
            X_transformed.shape[1]
        ),
        "feature_count": int(len(feature_names)),
        "feature_names": feature_names,
    }

    metadata_path = (
        OUTPUT_DIR
        / "explainability_metadata.json"
    )

    save_json(
        general_metadata,
        metadata_path
    )

    print(
        "Explainability metadata saved to:\n"
        f"{metadata_path}"
    )

    # --------------------------------------------------------
    # Completion message
    # --------------------------------------------------------

    print("\n" + "=" * 70)
    print("STEP 12 COMPLETED SUCCESSFULLY")
    print("=" * 70)

    print("\nGenerated files:")
    print(f"1. {shap_output_path}")
    print(f"2. {global_importance_path}")
    print(f"3. {critical_plot_path}")
    print(f"4. {summary_plot_path}")
    print(f"5. {local_explanation_path}")
    print(f"6. {local_metadata_path}")
    print(f"7. {metadata_path}")

    print("\nExplainability output folder:")
    print(OUTPUT_DIR)


# ============================================================
# 7. SCRIPT ENTRY POINT
# ============================================================

if __name__ == "__main__":
    main()